// Auto-generated by scripts/optimize-images.mjs
export const imageBlurs: Record<string, string> = {
  "director.webp": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACQAQCdASoKAAcABUB8JQAAS1n4Z8QA/LIvvCKasHwleRPSipMsmlDLUUJ1fseqQ4AAAA==",
  "hero.webp": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoKAAcABUB8JQBOgCPX1RushVgA8qVVIlsvFXkQFdSiQoUa4+56XptDer6rg+66OMyZAAAA",
  "about.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoKAAYABUB8JZQC7AD8LqEIbEAA/tHeE/g+k9sLdGPFUGIV5+5PSw7N8hTxZb3djLkhnCJ5QAAAAA==",
  "about-building.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAQAgCdASoKAAcABUB8JYwCsADdqqDXBOQAAP59S5iCDUmtyoV6kGry9Qep53R+lNi0vvt5mYAAAA==",
  "chairman-hero.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAABwAQCdASoKAAcABUB8JYwAApZoAAD+flFSOGIsUYpoejTms8t2x7+5UYUW/LAAAAA=",
  "investor-hero.webp": "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoKAAcABUB8JaQAA3AA/vDFXVs8AAAA",
  "land-bank-hero.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAAAQAgCdASoKAAcABUB8JQBdj+ACuN7ae0aAAP6I27tBfzVR1mZgFDth+maofCPgAAA=",
  "csr-hero.webp": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoKAAcABUB8JZgCdAEQzFzaX8AA/sB3ye4lT9mr3a/8fGnLvf+GXBkGQ91Yvt/b2uCR4AAA",
  "amenities-hero.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoKAAcABUB8JYwAAwbmyI8U4AD+50RWtNmmHpVnMTbcDSonLCuVKLv1A6Kvk+R5VvQgAA==",
  "gallery-01.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoKAAcABUB8JQBOgCPbDEdtAQAA8qVVaPgGnIBG7TMdfOj9VwDmWrgZnQD1TgtCYk4fLy0AAAA=",
  "gallery-02.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoKAAcABUB8JYwCsADcrW4Aj8AA/n1LmIINSa3Keb5DgHag9hvS7ARJXgh9DCPG1OAAAA==",
  "gallery-03.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoKAAYABUB8JZQC7AD8LqEIbEAA/tHeE/g+k9sLdGPFUGIV5+5PSw7N8hTxZb3djLkhnCJ5QAAAAA==",
  "gallery-04.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoKAAcABUB8JYwCdAD0t7Cp3gAAziYsC+kPUnJgLZH9zEWMiGMwjFCqhWX3zTeCltwAAA==",
  "gallery-05.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoKAAcABUB8JYwAAlgXZNyAAP7nRFa07KVDMgSmHVjttR3t1TvXlV5vtVS2b0xFfzgQAA==",
  "gallery-06.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAcABUB8JYwAApbwAAD+flFRxsocqZeP7XYFSjeBjwTYSR1IDwAA",
  "gallery-07.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoKAAcABUB8JbACdADc2NsQAPzhXYA8VuoeJPK96NVB0YA3lOd5qq70mLTGliBX7iKfgyoAAAA=",
  "gallery-08.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoKAAcABUB8JZgCdAEQ+cMS6IAA/HkavOdOcAGmWfiFZQPGOW3c3WvvCNdoVffH6sV86+Q0SxkrktAP4AA=",
  "gallery-09.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAQAgCdASoKAAcABUB8JYgCdAD8Lt/5PTAAAMxG9zSXPD5En5h6Q6QivyrH8gKWmKtRMX9E9AAAAA==",
  "gallery-10.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoKAAcABUB8JQBdgBszHAOgAP6Jrxz87QYuH0wBYghKXGd6IFkdm1fEoAA=",
  "gallery-11.webp": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACQAQCdASoKAAcABUB8JZwAAlJ7QgAAze91oe7aIgQ8xE3WQNWFMOu0AAA=",
  "gallery-12.webp": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoKAAcABUB8JbACdADZgoAAAP3qTnQ2wo8AFrLmMBOuROwYV/45d/FTBCSAAA==",
  "gallery-13.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAgCdASoKAAoABUB8JYwCdAEDfo1IWEIAAPdJTFzwitzd0kblRl8w7LNiBByZFMj633K1JQl0kBykQogjG+KAAAA=",
  "gallery-14.webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoKAAoABUB8JbACdAEfAymxnj0AAPj0Nkpe4ZUNRc9eFWfYpiK8w2q6uI24d2IZS3Thvoz6nag8FAAA",
  "gallery-15.webp": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoKAAoABUB8JQBOgBuwCe3GgAD2kAWPHPVJmJpW2YcG+EqFwwW9AuZji27efzyjdcsspQOvbBzFcI3UqATEAAAA",
  "gallery-16.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoKAAkABUB8JagC7ADdqyupTcAA/ru53EGgRNN/mtz0NGJCQpkpMkF7Jupe19UAAAA=",
  "gallery-17.webp": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoHAAoABUB8JYwCsADbI1cGQAD+RHnTwOVwaNiMxzJsj2+Db1TF36q6dVKDBUkfCvzMPIAA",
  "testimonial-01.webp": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACQAQCdASoKAAcABUB8JZwAAtRpzQAA/NIiAdAm3/6nu0uQNxATpYMQAAA=",
  "testimonial-02.webp": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoKAAcABUB8JYgCdADZodyQQAD8ju0jpaTR54rm0Ac2ZNko77g9Y6Q4BAi+fwmnIEIUvcgA",
  "testimonial-03.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAQAgCdASoHAAoABUB8JZQCw7EXftdGydgYAP4mynwZSOpKMqw4F4uTBLsLAoQDEDY4j4AA",
};

export function getImageBlur(src: string): string | undefined {
  const key = src.split("/").pop();
  return key ? imageBlurs[key] : undefined;
}
